### ISSUE TITLE
didemo_ret_val_new.json

### ISSUE THREAD

**Issue by tqosu** [mlvlab/vid-TLDR#1]
Dear authors,

What is didemo_ret_val_new.json?

**Comment by joonmyungchoi** [comment]
Thank you for your interest in our paper.

We noticed that in the "didemo_ret_val.json" provided by UMT, all files were preprocessed in the mp4 format. 
However, the raw data provided on the official website for didemo comprises various formats such as mp4, mov, etc. 
Consequently, we have created new annotation files to align with this format variation.

Once again, thank you for your attention and interest.

Best regards

**Comment by tqosu** [comment]
Thanks.
